name: Build & Deploy Flexidev Test App
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ghcr.io/smam-tech/flexidev-portal:main
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    # - name: Log in to Azure
    #   uses: azure/login@v2
    #   with:
    #     auth-type: IDENTITY
    #     enable-AzPSSession: true
    #     # client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      with:
        push: true
        tags: ${{ env.IMAGE_TAG }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ghcr.io/smam-tech/flexidev-portal:main
    steps:
    - name: Deploy to Azure Web App using GHCR image
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'smam-portal'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fd43a82d0f534adc8bf7728052df05fa }}
        images: ${{ env.IMAGE_TAG }}
