name: Build & Deploy Flexidev Test App
on:
  push:
    branches:
    - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: flexidev-portal
      IMAGE_TAG: latest
      GHCR_REGISTRY: ghcr.io
      GHCR_REPO: ghcr.io/${{ github.repository_owner }}/flexidev-portal
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Log in Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      push: true
      context: .
      file: ./Dockerfile
      tags: ${{ env.GHCR_REPO }}:${{ env.IMAGE_TAG }}
